#!/usr/bin/env python3
"""
WinStore - inspectdb helper

Generates Django models from the currently configured database using inspectdb.

Usage examples:
  - Generate all tables to backend/generated_models.py
      python backend/scripts/generate_models.py --output backend/generated_models.py

  - Generate specific tables to apps/products/models_inspected.py
      python backend/scripts/generate_models.py \
        --output backend/apps/products/models_inspected.py \
        --tables Products ProductAttributes Vendors Categories

  - Use a different database alias (if defined in settings.DATABASES)
      python backend/scripts/generate_models.py --database reporting --output backend/generated_models.py

Notes:
  - The script uses the active Django settings (config.settings). Adjust DATABASES there
    to point to Oracle or PostgreSQL before running.
  - Output models will have managed = False by default (Django behavior for inspectdb).
"""

import os
import sys
import io
import argparse
from datetime import datetime


def bootstrap_django():
    # Ensure we can import config.settings when running from repo root
    backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, backend_dir)
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    try:
        import django  # noqa: F401
        django.setup()
    except Exception as e:
        sys.stderr.write(f"Failed to initialize Django. Ensure settings are correct.\n{e}\n")
        sys.exit(1)


def run_inspectdb(output_path: str, database: str, tables: list[str] | None):
    from django.core.management import call_command

    buf = io.StringIO()
    call_kwargs = {'stdout': buf, 'database': database}

    # If specific tables provided, pass them positionally
    if tables:
        call_command('inspectdb', *tables, **call_kwargs)
    else:
        call_command('inspectdb', **call_kwargs)

    content = buf.getvalue()

    # Prepend a small header
    header = (
        "# Generated by inspectdb\n"
        f"# Timestamp: {datetime.utcnow().isoformat()}Z\n"
        f"# Database alias: {database}\n\n"
    )
    final = header + content

    # Ensure directory exists
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final)

    print(f"Models written to: {output_path}")


def parse_args(argv: list[str]):
    p = argparse.ArgumentParser(description='Generate Django models via inspectdb.')
    p.add_argument('--output', required=True, help='Path to write generated models.py')
    p.add_argument('--database', default='default', help='DATABASES alias to use (default: default)')
    p.add_argument('--tables', nargs='*', help='Optional list of table names to include (space-separated)')
    return p.parse_args(argv)


def main(argv: list[str] | None = None):
    args = parse_args(argv or sys.argv[1:])
    bootstrap_django()
    run_inspectdb(output_path=args.output, database=args.database, tables=args.tables)


if __name__ == '__main__':
    main()
